//! Confine the Python kernel with a macOS Seatbelt profile.
//!
//! `bash` is sandboxed inside the harness by the gate extension, but the other
//! built-in tool — `ipython` — executes in a long-lived kernel process the
//! harness spawns itself, out of the gate's reach. The one seam the harness
//! does offer is `PRIME_AGENT_KERNEL_PYTHON`: point it at an interpreter and
//! the kernel uses that instead of the bootstrapped venv python.
//!
//! So we point it at a wrapper that re-executes the real venv python under
//! `sandbox-exec`. No harness change, and it applies to every code cell the
//! model runs.
//!
//! ## What the profile enforces
//!
//! `(allow default)` with targeted denials, not `(deny default)` with an
//! allow-list. A deny-default profile for a Python interpreter means
//! enumerating every dylib, locale file, and framework CPython touches —
//! derivable only by bisecting against a running kernel, and brittle across
//! Python versions. This is a containment measure with a stated scope:
//!
//! * **writes** are denied everywhere except the workspace, temp dirs, and the
//!   agent's own session-artifact directory (where kernel snapshots live);
//! * **credential files** are unreadable — ssh, aws, gnupg keys, and the
//!   agent's own `auth.json`, so a code cell cannot exfiltrate the API keys
//!   that pay for it;
//! * **network is untouched** — a code cell can still reach the internet, the
//!   same as `bash`.
//!
//! Reads outside those files are allowed. This narrows blast radius; it does
//! not make untrusted code safe to run.
//!
//! macOS only. `sandbox-exec` is deprecated but is what Apple still ships and
//! what other agent desktop apps use for the same job; on other platforms the
//! kernel runs unconfined and the approval prompt remains the only control.

use std::path::{Path, PathBuf};

use super::error::AppError;

/// Seatbelt profile source. Paths arrive as `-D` parameters rather than being
/// interpolated, so no path can alter the policy's structure.
const PROFILE: &str = r#"(version 1)

;; Containment, not isolation — see kernel_sandbox.rs for the threat model.
(allow default)

;; ── Writes: workspace and scratch only ──────────────────────────────
(deny file-write*)
(allow file-write*
  (subpath (param "WORKSPACE"))
  (subpath (param "ARTIFACTS"))
  (subpath (param "TMPDIR"))
  (subpath "/private/tmp")
  (subpath "/private/var/folders")
  (subpath "/private/var/tmp"))
(allow file-write-data
  (literal "/dev/null")
  (literal "/dev/stdout")
  (literal "/dev/stderr")
  (literal "/dev/dtracehelper"))

;; ── Credentials stay unreadable ─────────────────────────────────────
(deny file-read*
  (subpath (param "SSH_DIR"))
  (subpath (param "AWS_DIR"))
  (subpath (param "GNUPG_DIR"))
  (subpath (param "GH_DIR"))
  (literal (param "NETRC"))
  (literal (param "AUTH_JSON"))
  (literal (param "MODELS_JSON")))
"#;

/// Where the generated profile and wrapper live. Inside the agent's own
/// directory so they sit next to the venv they wrap and are removed with it.
fn sandbox_dir() -> Result<PathBuf, AppError> {
    let home = dirs::home_dir().ok_or_else(|| AppError::Other("no home directory".into()))?;
    Ok(home.join(".prime/agent/laf-sandbox"))
}

/// The bootstrapped kernel interpreter, if it exists yet.
pub fn kernel_venv_python() -> Option<PathBuf> {
    let python = dirs::home_dir()?.join(".prime/agent/kernel-venv/bin/python");
    python.exists().then_some(python)
}

/// Build (or refresh) the sandbox wrapper for `workspace` and return its path.
///
/// Returns `Ok(None)` when the kernel has not been bootstrapped yet — the
/// harness must run its own bootstrap first, and that is our code, not the
/// model's. Also returns `Ok(None)` off macOS.
pub fn wrapper_for(workspace: &str) -> Result<Option<PathBuf>, AppError> {
    if !cfg!(target_os = "macos") {
        return Ok(None);
    }
    if !Path::new("/usr/bin/sandbox-exec").exists() {
        return Ok(None);
    }
    let Some(python) = kernel_venv_python() else {
        return Ok(None);
    };
    let home = dirs::home_dir().ok_or_else(|| AppError::Other("no home directory".into()))?;
    let dir = sandbox_dir()?;
    std::fs::create_dir_all(&dir)?;

    let profile_path = dir.join("kernel.sb");
    std::fs::write(&profile_path, PROFILE)?;

    // A workspace that does not exist yet would make sandbox-exec reject the
    // profile, so fall back to the agent dir — writes there are already
    // allowed and the kernel simply gets no project scope.
    let workspace_param = if Path::new(workspace).is_dir() {
        workspace.to_string()
    } else {
        home.join(".prime/agent").to_string_lossy().to_string()
    };
    let agent_dir = home.join(".prime/agent");
    let tmpdir = std::env::var("TMPDIR").unwrap_or_else(|_| "/private/tmp".to_string());

    let param = |k: &str, v: String| format!("  -D {k}={}", shell_quote(&v));
    let wrapper = format!(
        "#!/bin/sh\n\
         # Generated by LAF Agent — see src-tauri/src/commands/kernel_sandbox.rs\n\
         # Re-execs the kernel interpreter under a Seatbelt profile.\n\
         exec /usr/bin/sandbox-exec \\\n\
         {params} \\\n\
         \x20 -f {profile} \\\n\
         \x20 {python} \"$@\"\n",
        params = [
            param("WORKSPACE", workspace_param),
            param("ARTIFACTS", agent_dir.to_string_lossy().to_string()),
            param("TMPDIR", trim_trailing_slash(&tmpdir)),
            param("SSH_DIR", home.join(".ssh").to_string_lossy().to_string()),
            param("AWS_DIR", home.join(".aws").to_string_lossy().to_string()),
            param("GNUPG_DIR", home.join(".gnupg").to_string_lossy().to_string()),
            param("GH_DIR", home.join(".config/gh").to_string_lossy().to_string()),
            param("NETRC", home.join(".netrc").to_string_lossy().to_string()),
            param("AUTH_JSON", agent_dir.join("auth.json").to_string_lossy().to_string()),
            param("MODELS_JSON", agent_dir.join("models.json").to_string_lossy().to_string()),
        ]
        .join(" \\\n"),
        profile = shell_quote(&profile_path.to_string_lossy()),
        python = shell_quote(&python.to_string_lossy()),
    );

    let wrapper_path = dir.join("kernel-python");
    std::fs::write(&wrapper_path, wrapper)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&wrapper_path, std::fs::Permissions::from_mode(0o755))?;
    }
    Ok(Some(wrapper_path))
}

/// `sandbox-exec` rejects a subpath with a trailing slash.
fn trim_trailing_slash(p: &str) -> String {
    p.strip_suffix('/').unwrap_or(p).to_string()
}

/// Single-quote for `/bin/sh`, closing and reopening around embedded quotes.
fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shell_quote_wraps_plain_paths() {
        assert_eq!(shell_quote("/usr/bin/python"), "'/usr/bin/python'");
    }

    #[test]
    fn shell_quote_survives_a_real_shell() {
        // Asserting on the quoted text proves nothing — `'\''` legitimately
        // contains `'`. Ask /bin/sh what it actually parsed instead.
        let hostile = "/tmp/it's here'; touch /tmp/laf-injection-canary; echo '";
        let out = std::process::Command::new("/bin/sh")
            .arg("-c")
            .arg(format!("printf %s {}", shell_quote(hostile)))
            .output()
            .expect("sh should run");
        assert_eq!(String::from_utf8_lossy(&out.stdout), hostile);
        assert!(!Path::new("/tmp/laf-injection-canary").exists(), "injection ran");
    }

    #[test]
    fn trailing_slash_is_trimmed_for_subpath() {
        assert_eq!(trim_trailing_slash("/private/tmp/"), "/private/tmp");
        assert_eq!(trim_trailing_slash("/private/tmp"), "/private/tmp");
    }

    #[test]
    fn profile_parameterizes_every_path() {
        // Structure must come from the profile, never from a runtime string.
        for key in [
            "WORKSPACE", "ARTIFACTS", "TMPDIR", "SSH_DIR", "AWS_DIR", "GNUPG_DIR", "GH_DIR",
            "NETRC", "AUTH_JSON", "MODELS_JSON",
        ] {
            assert!(PROFILE.contains(&format!("(param \"{key}\")")), "missing param {key}");
        }
        assert!(PROFILE.contains("(deny file-write*)"));
    }
}
